version: '3'

services:
  sim_rest:
    build: .
    entrypoint: ./sim.py sim_rest.rest.0.0.0 -d sim_user.rest.0.0.0 -d sim_videos.rest.0.0.0
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - FLASK_ENV
    deploy:
      mode: replicated
      replicas: 2

  sim_user:
    build: .
    entrypoint: ./sim.py sim_user.rest.0.0.0
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - FLASK_ENV
    deploy:
      mode: replicated
      replicas: 2

  sim_videos:
    build: .
    entrypoint: ./sim.py sim_videos.rest.0.0.0 -d sim_user.rest.0.0.0
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - FLASK_ENV
    deploy:
      mode: replicated
      replicas: 2

  sim_chat:
    build: .
    entrypoint: ./sim.py sim_chat.rest.0.0.0 -d sim_user.rest.0.0.0 -d sim_rest.rest.0.0.0 -d nothing --heartbeat 0
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - FLASK_ENV
    deploy:
      mode: replicated
      replicas: 1

  sim_unused:
    build: .
    entrypoint: ./sim.py sim_unused.rest.0.0.0 -d sim_user.rest.0.0.0 -d sim_rest.rest.0.0.0
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - FLASK_ENV
    deploy:
      mode: replicated
      replicas: 1



