version: '3'

services:
  registry:
    build: .
    entrypoint: ./registry.py --heartbeat=20 --port=5000
    ports:
      - ${REGISTRY_PORT:-5000}:5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV
      - FLASK_DEBUG=0
  dns:
    build: .
    entrypoint: ./dns.py --registry=registry:${REGISTRY_PORT:-5000}
    ports:
      - ${DNS_PORT:-5053}:5053/udp
      - ${DNS_PORT:-5053}:5053/tcp
    depends_on:
      - registry
    volumes:
      - .:/app
    environment:
      - FLASK_ENV
      - FLASK_DEBUG=0